---
title: "lesson4_problem_set"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Set up diamond data

```{r}
library(ggplot2)
data("diamonds")
summary(diamonds)
```

###Quiz 1

```{r}
dim(diamonds)

is.factor(diamonds$depth)
is.ordered((diamonds$carat))

?diamonds
```

###Quiz 2

```{r}
qplot(data = diamonds, x = diamonds$price, binwidth = 100,
      color = I('black'), fill = I("blue"))
```

###Quiz 3

```{r}
summary(diamonds$price)
```
The graph is long-tailed and skewed right so the center is towards the left. To be exact:

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    326     950    2401    3933    5324   18823 
    
###Quiz 4

```{r}
dim(subset(diamonds, price < 500))
dim(subset(diamonds, price < 250))
dim(subset(diamonds, price >= 15000))
```

###Quiz 5

```{r}
qplot(data = diamonds, x = diamonds$price, binwidth = 100,
      color = I('black'), fill = I("blue")) + 
  scale_x_continuous(limits = c(0, 2500), breaks = seq(0, 2500, 500))
```

###Quiz 6

```{r}
cut1 = qplot(data = subset(diamonds, diamonds$cut == 'Fair'), x = price)
cut2 = qplot(data = subset(diamonds, diamonds$cut == 'Good'), x = price)
cut3 = qplot(data = subset(diamonds, diamonds$cut == 'Very Good'), x = price)
cut4 = qplot(data = subset(diamonds, diamonds$cut == 'Premium'), x = price)
cut5 = qplot(data = subset(diamonds, diamonds$cut == 'Ideal'), x = price)
grid.arrange(cut1, cut2, cut3, cut4, cut5, ncol = 2)
```

###Quiz 7

```{r}
by(diamonds$price, diamonds$cut, summary)
```

###Quiz 8

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~cut)

#makes the scales free in the y-axis
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales = "free_y")
```

###Quiz 9

```{r}
qplot(x = price/carat, data = diamonds) + 
  facet_wrap(~cut, scales = "free_y") +
  scale_x_log10()

```

###Quiz 10

```{r}
by(diamonds$price, diamonds$clarity, summary)
by(diamonds$price/diamonds$carat, diamonds$clarity, summary)

p1 = qplot(data = diamonds, x = clarity, y = price, geom = 'boxplot') +
  coord_cartesian(ylim = c(0, 6000))

p2 = qplot(data = diamonds, x = clarity, y = price/carat, geom = 'boxplot') +
  coord_cartesian(ylim = c(2000, 6000))

grid.arrange(p1, p2)
ggsave("priceHistogram.png")
```

###Quiz 11

```{r}
by(diamonds$price, diamonds$color, summary)
```

###Quiz 12

```{r}
p1 = qplot(x = color, y = price, data = diamonds, geom = "boxplot") +
  coord_cartesian(ylim = c(0, 8000))

p2 = qplot(x = color, y = price/carat, data = diamonds, geom = "boxplot") +
  coord_cartesian(ylim = c(2000, 6000))

ggsave("price_by_color_hist.png")
by(diamonds$price/diamonds$carat, diamonds$color, summary)
```

###Quiz 13

```{r}
qplot(x = carat, y = ..count.., data = diamonds, geom = 'freqpoly', 
      binwidth = 0.1,
      ylab = "Number of Diamonds",
      xlab = "Carats") +
  scale_x_continuous(lim = c(0, 2.5), breaks = seq(0, 2.5, 0.1)) +
  scale_y_continuous(lim = c(0, 11000), breaks = seq(0, 11000, 1000))
```

###Quiz 14

```{r}
sugar <- read.csv("sugar_consumption.csv", header = T, row.names = 1, check.names = F)
?read.table
transposed_sugar <- as.data.frame(t(sugar))
names(transposed_sugar)
row.names(transposed_sugar)
transposed_sugar
#remove all columns that are empty
transposed_sugar[sapply( X = transposed_sugar, FUN =  function(x) all(is.na(x)))] <- NULL
transposed_sugar
qplot(data = transposed_sugar, x = Philippines)
```


